### ISSUE TITLE
atmosphere-spring broken against Spring 4

### ISSUE THREAD

**Issue by jvergara65** [Atmosphere/atmosphere-extensions#193]
I am using  atmosphere-spring 2.3.1,  atmosphere-runtime 2.3.3 and Spring 4.0.8
I am getting the following error

java.lang.NoSuchMethodError: org.springframework.context.annotation.AnnotationConfigApplicationContext.getBean(Ljava/lang/Class;[Ljava/lang/Object;)Ljava/lang/Object;
	at org.atmosphere.spring.SpringWebObjectFactory.configure(SpringWebObjectFactory.java:90)
	at org.atmosphere.cpr.AtmosphereFramework.lookupDefaultObjectFactoryType(AtmosphereFramework.java:1693)
	at org.atmosphere.cpr.AtmosphereFramework.init(AtmosphereFramework.java:877)
	at org.atmosphere.cpr.AtmosphereFramework.init(AtmosphereFramework.java:835)
	at org.atmosphere.cpr.AtmosphereFrameworkInitializer.configureFramework(AtmosphereFrameworkInitializer.java:74)
	at org.atmosphere.cpr.AtmosphereServlet.configureFramework(AtmosphereServlet.java:83)
	at org.atmosphere.cpr.AtmosphereServlet.configureFramework(AtmosphereServlet.java:79)
	at org.atmosphere.cpr.AtmosphereServlet.init(AtmosphereServlet.java:74)
	at org.atmosphere.cpr.MeteorServlet.init(MeteorServlet.java:88)
	at weblogic.servlet.internal.StubSecurityHelper$ServletInitAction.run(StubSecurityHelper.java:283)
	at weblogic.security.acl.internal.AuthenticatedSubject.doAs(AuthenticatedSubject.java:321)
	at weblogic.security.service.SecurityManager.runAs(SecurityManager.java:120)
	at weblogic.servlet.internal.StubSecurityHelper.createServlet(StubSecurityHelper.java:64)
	at weblogic.serv

How can I get this to work?

**Comment by jfarcand** [comment]
Use the mailingh list for question: https://groups.google.com/group/atmosphere-framework?pli=1
