### ISSUE TITLE
GWT 2.0 extension - multiple messages broadcasted at the same time fail to deserialize at client

### ISSUE THREAD

**Issue by Raveler** [Atmosphere/atmosphere-extensions#76]
This can easily be replicated with the gwt20-rpc example.

In GwtRpcAtmosphereHandler, just broadcast each incoming message three times:
                DefaultBroadcasterFactory.getDefault().lookup("RPC").broadcast(obj);
                DefaultBroadcasterFactory.getDefault().lookup("RPC").broadcast(obj);
                DefaultBroadcasterFactory.getDefault().lookup("RPC").broadcast(obj);

This will trigger a deserialization error at the client. If you print the data that arrives at the RPCSerializer, you get the following:

[2,1,["org.atmosphere.samples.client.RPCEvent/1961505988","vxvcvxxv"],0,7][2,1,["org.atmosphere.samples.client.RPCEvent/1961505988","vxvcvxxv"],0,7]

The two messages are appended after each other in the same data chunk, which triggers an exception in the deserializer:

com.google.gwt.user.client.rpc.SerializationException: Failed to parse RPC payload
   at com.google.gwt.user.client.rpc.impl.ClientSerializationStreamReader.prepareToRead(ClientSerializationStreamReader.java:322)
   at org.atmosphere.extensions.gwt20.client.GwtRpcClientSerializer.deserialize(GwtRpcClientSerializer.java:74)
   at org.atmosphere.samples.client.RPCSerializer.deserialize(RPCSerializer.java:33)
   at org.atmosphere.extensions.gwt20.client.AtmosphereRequestConfig$MessageHandlerWrapper.onMessage(AtmosphereRequestConfig.java:258)
   at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
   at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
   at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
   at java.lang.reflect.Method.invoke(Method.java:597)
   at com.google.gwt.dev.shell.MethodAdaptor.invoke(MethodAdaptor.java:103)
   at com.google.gwt.dev.shell.MethodDispatch.invoke(MethodDispatch.java:71)
   at com.google.gwt.dev.shell.OophmSessionHandler.invoke(OophmSessionHandler.java:172)
   at com.google.gwt.dev.shell.BrowserChannelServer.reactToMessagesWhileWaitingForReturn(BrowserChannelServer.java:338)
   at com.google.gwt.dev.shell.BrowserChannelServer.invokeJavascript(BrowserChannelServer.java:219)
   at com.google.gwt.dev.shell.ModuleSpaceOOPHM.doInvoke(ModuleSpaceOOPHM.java:136)
   at com.google.gwt.dev.shell.ModuleSpace.invokeNative(ModuleSpace.java:571)
   at com.google.gwt.dev.shell.ModuleSpace.invokeNativeObject(ModuleSpace.java:279)
   at com.google.gwt.dev.shell.JavaScriptHost.invokeNativeObject(JavaScriptHost.java:91)
   at com.google.gwt.core.client.impl.Impl.apply(Impl.java)
   at com.google.gwt.core.client.impl.Impl.entry0(Impl.java:242)
   at sun.reflect.GeneratedMethodAccessor25.invoke(Unknown Source)
   at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
   at java.lang.reflect.Method.invoke(Method.java:597)
   at com.google.gwt.dev.shell.MethodAdaptor.invoke(MethodAdaptor.java:103)
   at com.google.gwt.dev.shell.MethodDispatch.invoke(MethodDispatch.java:71)
   at com.google.gwt.dev.shell.OophmSessionHandler.invoke(OophmSessionHandler.java:172)
   at com.google.gwt.dev.shell.BrowserChannelServer.reactToMessages(BrowserChannelServer.java:293)
   at com.google.gwt.dev.shell.BrowserChannelServer.processConnection(BrowserChannelServer.java:547)
   at com.google.gwt.dev.shell.BrowserChannelServer.run(BrowserChannelServer.java:364)
   at java.lang.Thread.run(Thread.java:662)
Caused by: com.google.gwt.dev.jjs.InternalCompilerException: Unexpected error during visit.
   at com.google.gwt.dev.js.ast.JsVisitor.translateException(JsVisitor.java:483)
   at com.google.gwt.dev.js.ast.JsVisitor.doTraverse(JsVisitor.java:470)
   at com.google.gwt.dev.js.ast.JsVisitor.doAccept(JsVisitor.java:445)
   at com.google.gwt.dev.js.ast.JsVisitor.accept(JsVisitor.java:109)
   at com.google.gwt.dev.js.ast.JsBinaryOperation.traverse(JsBinaryOperation.java:118)
   at com.google.gwt.dev.js.ast.JsVisitor.doTraverse(JsVisitor.java:468)
   at com.google.gwt.dev.js.ast.JsVisitor.doAccept(JsVisitor.java:445)
   at com.google.gwt.dev.js.ast.JsVisitor.accept(JsVisitor.java:109)
   at com.google.gwt.dev.js.ast.JsBinaryOperation.traverse(JsBinaryOperation.java:116)
   at com.google.gwt.dev.js.ast.JsVisitor.doTraverse(JsVisitor.java:468)
   at com.google.gwt.dev.js.ast.JsVisitor.doAccept(JsVisitor.java:445)
   at com.google.gwt.dev.js.ast.JsVisitor.accept(JsVisitor.java:109)
   at com.google.gwt.dev.js.ast.JsBinaryOperation.traverse(JsBinaryOperation.java:116)
   at com.google.gwt.dev.js.ast.JsVisitor.doTraverse(JsVisitor.java:468)
   at com.google.gwt.dev.js.ast.JsVisitor.doAccept(JsVisitor.java:445)
   at com.google.gwt.dev.js.ast.JsVisitor.accept(JsVisitor.java:109)
   at com.google.gwt.dev.js.ast.JsArrayAccess.traverse(JsArrayAccess.java:77)
   at com.google.gwt.dev.js.ast.JsVisitor.doTraverse(JsVisitor.java:468)
   at com.google.gwt.dev.js.ast.JsVisitor.doAccept(JsVisitor.java:445)
   at com.google.gwt.dev.js.ast.JsVisitor.accept(JsVisitor.java:109)
   at com.google.gwt.dev.js.ast.JsExprStmt.traverse(JsExprStmt.java:42)
   at com.google.gwt.dev.js.ast.JsVisitor.doTraverse(JsVisitor.java:468)
   at com.google.gwt.dev.js.ast.JsVisitor.doAcceptList(JsVisitor.java:451)
   at com.google.gwt.dev.js.ast.JsVisitor.acceptList(JsVisitor.java:113)
   at com.google.gwt.user.client.rpc.impl.ClientSerializationStreamReader.prepareToRead(ClientSerializationStreamReader.java:320)
   at org.atmosphere.extensions.gwt20.client.GwtRpcClientSerializer.deserialize(GwtRpcClientSerializer.java:74)
   at org.atmosphere.samples.client.RPCSerializer.deserialize(RPCSerializer.java:33)
   at org.atmosphere.extensions.gwt20.client.AtmosphereRequestConfig$MessageHandlerWrapper.onMessage(AtmosphereRequestConfig.java:258)
   at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
   at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
   at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
   at java.lang.reflect.Method.invoke(Method.java:597)
   at com.google.gwt.dev.shell.MethodAdaptor.invoke(MethodAdaptor.java:103)
   at com.google.gwt.dev.shell.MethodDispatch.invoke(MethodDispatch.java:71)
   at com.google.gwt.dev.shell.OophmSessionHandler.invoke(OophmSessionHandler.java:172)
   at com.google.gwt.dev.shell.BrowserChannelServer.reactToMessagesWhileWaitingForReturn(BrowserChannelServer.java:338)
   at com.google.gwt.dev.shell.BrowserChannelServer.invokeJavascript(BrowserChannelServer.java:219)
   at com.google.gwt.dev.shell.ModuleSpaceOOPHM.doInvoke(ModuleSpaceOOPHM.java:136)
   at com.google.gwt.dev.shell.ModuleSpace.invokeNative(ModuleSpace.java:571)
   at com.google.gwt.dev.shell.ModuleSpace.invokeNativeObject(ModuleSpace.java:279)
   at com.google.gwt.dev.shell.JavaScriptHost.invokeNativeObject(JavaScriptHost.java:91)
   at com.google.gwt.core.client.impl.Impl.apply(Impl.java)
   at com.google.gwt.core.client.impl.Impl.entry0(Impl.java:242)
   at sun.reflect.GeneratedMethodAccessor25.invoke(Unknown Source)
   at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
   at java.lang.reflect.Method.invoke(Method.java:597)
   at com.google.gwt.dev.shell.MethodAdaptor.invoke(MethodAdaptor.java:103)
   at com.google.gwt.dev.shell.MethodDispatch.invoke(MethodDispatch.java:71)
   at com.google.gwt.dev.shell.OophmSessionHandler.invoke(OophmSessionHandler.java:172)
   at com.google.gwt.dev.shell.BrowserChannelServer.reactToMessages(BrowserChannelServer.java:293)
   at com.google.gwt.dev.shell.BrowserChannelServer.processConnection(BrowserChannelServer.java:547)
   at com.google.gwt.dev.shell.BrowserChannelServer.run(BrowserChannelServer.java:364)
   at java.lang.Thread.run(Thread.java:662)
Caused by: java.lang.RuntimeException: Unexpected array in RPC payload. The string table has already started.
   at com.google.gwt.user.client.rpc.impl.ClientSerializationStreamReader$RpcDecoder.visit(ClientSerializationStreamReader.java:122)
   at com.google.gwt.dev.js.ast.JsArrayLiteral.traverse(JsArrayLiteral.java:73)
   at com.google.gwt.dev.js.ast.JsVisitor.doTraverse(JsVisitor.java:468)
   at com.google.gwt.dev.js.ast.JsVisitor.doAccept(JsVisitor.java:445)
   at com.google.gwt.dev.js.ast.JsVisitor.accept(JsVisitor.java:109)
   at com.google.gwt.dev.js.ast.JsBinaryOperation.traverse(JsBinaryOperation.java:118)
   at com.google.gwt.dev.js.ast.JsVisitor.doTraverse(JsVisitor.java:468)
   at com.google.gwt.dev.js.ast.JsVisitor.doAccept(JsVisitor.java:445)
   at com.google.gwt.dev.js.ast.JsVisitor.accept(JsVisitor.java:109)
   at com.google.gwt.dev.js.ast.JsBinaryOperation.traverse(JsBinaryOperation.java:116)
   at com.google.gwt.dev.js.ast.JsVisitor.doTraverse(JsVisitor.java:468)
   at com.google.gwt.dev.js.ast.JsVisitor.doAccept(JsVisitor.java:445)
   at com.google.gwt.dev.js.ast.JsVisitor.accept(JsVisitor.java:109)
   at com.google.gwt.dev.js.ast.JsBinaryOperation.traverse(JsBinaryOperation.java:116)
   at com.google.gwt.dev.js.ast.JsVisitor.doTraverse(JsVisitor.java:468)
   at com.google.gwt.dev.js.ast.JsVisitor.doAccept(JsVisitor.java:445)
   at com.google.gwt.dev.js.ast.JsVisitor.accept(JsVisitor.java:109)
   at com.google.gwt.dev.js.ast.JsArrayAccess.traverse(JsArrayAccess.java:77)
   at com.google.gwt.dev.js.ast.JsVisitor.doTraverse(JsVisitor.java:468)
   at com.google.gwt.dev.js.ast.JsVisitor.doAccept(JsVisitor.java:445)
   at com.google.gwt.dev.js.ast.JsVisitor.accept(JsVisitor.java:109)
   at com.google.gwt.dev.js.ast.JsExprStmt.traverse(JsExprStmt.java:42)
   at com.google.gwt.dev.js.ast.JsVisitor.doTraverse(JsVisitor.java:468)
   at com.google.gwt.dev.js.ast.JsVisitor.doAcceptList(JsVisitor.java:451)
   at com.google.gwt.dev.js.ast.JsVisitor.acceptList(JsVisitor.java:113)
   at com.google.gwt.user.client.rpc.impl.ClientSerializationStreamReader.prepareToRead(ClientSerializationStreamReader.java:320)
   at org.atmosphere.extensions.gwt20.client.GwtRpcClientSerializer.deserialize(GwtRpcClientSerializer.java:74)
   at org.atmosphere.samples.client.RPCSerializer.deserialize(RPCSerializer.java:33)
   at org.atmosphere.extensions.gwt20.client.AtmosphereRequestConfig$MessageHandlerWrapper.onMessage(AtmosphereRequestConfig.java:258)
   at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
   at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
   at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
   at java.lang.reflect.Method.invoke(Method.java:597)
   at com.google.gwt.dev.shell.MethodAdaptor.invoke(MethodAdaptor.java:103)
   at com.google.gwt.dev.shell.MethodDispatch.invoke(MethodDispatch.java:71)
   at com.google.gwt.dev.shell.OophmSessionHandler.invoke(OophmSessionHandler.java:172)
   at com.google.gwt.dev.shell.BrowserChannelServer.reactToMessagesWhileWaitingForReturn(BrowserChannelServer.java:338)
   at com.google.gwt.dev.shell.BrowserChannelServer.invokeJavascript(BrowserChannelServer.java:219)
   at com.google.gwt.dev.shell.ModuleSpaceOOPHM.doInvoke(ModuleSpaceOOPHM.java:136)
   at com.google.gwt.dev.shell.ModuleSpace.invokeNative(ModuleSpace.java:571)
   at com.google.gwt.dev.shell.ModuleSpace.invokeNativeObject(ModuleSpace.java:279)
   at com.google.gwt.dev.shell.JavaScriptHost.invokeNativeObject(JavaScriptHost.java:91)
   at com.google.gwt.core.client.impl.Impl.apply(Impl.java)
   at com.google.gwt.core.client.impl.Impl.entry0(Impl.java:242)
   at sun.reflect.GeneratedMethodAccessor25.invoke(Unknown Source)
   at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
   at java.lang.reflect.Method.invoke(Method.java:597)
   at com.google.gwt.dev.shell.MethodAdaptor.invoke(MethodAdaptor.java:103)
   at com.google.gwt.dev.shell.MethodDispatch.invoke(MethodDispatch.java:71)
   at com.google.gwt.dev.shell.OophmSessionHandler.invoke(OophmSessionHandler.java:172)
   at com.google.gwt.dev.shell.BrowserChannelServer.reactToMessages(BrowserChannelServer.java:293)
   at com.google.gwt.dev.shell.BrowserChannelServer.processConnection(BrowserChannelServer.java:547)
   at com.google.gwt.dev.shell.BrowserChannelServer.run(BrowserChannelServer.java:364)
   at java.lang.Thread.run(Thread.java:662)

**Comment by hrvatees** [comment]
Hi,
4 years later, I'm trying to user Atmosphere to replace gwt-comet in my GWT 2.7 application.
I'm facing the exact same problem with the same test case but with a new version of Atmosphere (2.4.5).

Everything works fine when sending a single message, but if I send several messages, i get a SerializationException...

I've tried all the answers but none of them work... I'm looking for some help here

**Comment by jfarcand** [comment]
@hrvatees Strange...but use a newer version of Atmosphere AND atmosphere-gwt extensions.

**Comment by hrvatees** [comment]
Hi jfarcand,
Thanks for the fast answer.
I retrieved the whole gwt20-rpc project from github (GWT 2.5.1, Atmosphere 2.4.20), ran it on Tomcat 8 and I get the same error.

I've just tripled the broadcasting line in GwtRpcAtmosphereHandler.java
```
ar.getAtmosphereConfig().getBroadcasterFactory().lookup("MyBroadcaster").broadcast(msg);
ar.getAtmosphereConfig().getBroadcasterFactory().lookup("MyBroadcaster").broadcast(msg);
ar.getAtmosphereConfig().getBroadcasterFactory().lookup("MyBroadcaster").broadcast(msg); 
```

in Firefox and Chrome, I get the following exception 
```
Fri May 18 16:49:09 GMT+200 2018 com.google.gwt.core.client.JavaScriptObject$ SEVERE: Failed to deserialize message: [3,2,2,1,["org.atmosphere.samples.shared.EventBar/4037383378","test","EventBar"],0,7][3,2,2,1,["org.atmosphere.samples.shared.EventBar/4037383378","test","EventBar"],0,7][3,2,2,1,["org.atmosphere.samples.shared.EventBar/4037383378","test","EventBar"],0,7]
com.google.gwt.user.client.rpc.SerializationException: com.google.gwt.core.client.JavaScriptException: (TypeError) : [3, 2, 2, 1, ["org.atmosphere.samples.shared.EventBar/4037383378", "test", "EventBar"], 0, 7][7] is undefined
   at Unknown.collect_0(Unknown Source)
   at Unknown.createStackTrace(Unknown Source)
   at Unknown.fillInStackTrace_0(Unknown Source)
   at Unknown.fillInStackTrace(Unknown Source)
   at Unknown.$fillInStackTrace(Unknown Source)
   at Unknown.$$init_0(Unknown Source)
   at Unknown.Throwable_3(Unknown Source)
   at Unknown.Exception_3(Unknown Source)
   at Unknown.SerializationException_1(Unknown Source)
   at Unknown.deserialize_2(Unknown Source)
   at Unknown.onMessage(Unknown Source)
   at Unknown.$setMessageHandlerImpl/this$static.onMessage<(Unknown Source)
   at Unknown.apply(Unknown Source)
   at Unknown.entry0(Unknown Source)
   at Unknown.entry_0/<(Unknown Source)
   at Unknown._f(Unknown Source)
   at Unknown._invokeFunction(Unknown Source)
   at Unknown._invokeCallback(Unknown Source)
   at Unknown._executeRequest/ajaxRequest.onreadystatechange(Unknown Source)
   at Unknown.anonymous(Unknown Source)
Caused by: com.google.gwt.core.client.JavaScriptException: (TypeError) : [3, 2, 2, 1, ["org.atmosphere.samples.shared.EventBar/4037383378", "test", "EventBar"], 0, 7][7] is undefined
   at Unknown.anonymous(Unknown Source)
   at Unknown.eval_0(Unknown Source)
   at Unknown.$prepareToRead_0(Unknown Source)
   at Unknown.deserialize_2(Unknown Source)
   at Unknown.onMessage(Unknown Source)
   at Unknown.$setMessageHandlerImpl/this$static.onMessage<(Unknown Source)
   at Unknown.apply(Unknown Source)
   at Unknown.entry0(Unknown Source)
   at Unknown.entry_0/<(Unknown Source)
   at Unknown._f(Unknown Source)
   at Unknown._invokeFunction(Unknown Source)
   at Unknown._invokeCallback(Unknown Source)
   at Unknown._executeRequest/ajaxRequest.onreadystatechange(Unknown Source)
   at Unknown.anonymous(Unknown Source)
```

Thanks for your help

**Comment by hrvatees** [comment]
For information, I've just tried the gwt-json project with the same changes and I received the message 3 times. Seems to work fine... Should I migrate ?
